schedules:
  - cron: "30 7 * * *"
    displayName: Daily build 7:30AM
    always: true
    branches:
      include:
        - test

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: serviceConnection
    value: ODB_DEVOPS
steps:
  - task: JavaToolInstaller@0
    displayName: '[Precheck]: Use Java 21'
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  #- task: ms-autotest.screen-resolution-utility-task.screen-resolution-utlity-task.ScreenResolutionUtility@1
    #displayName: '[Precheck]: Set Screen Resolution'

#  - task: DockerCompose@1
#    displayName: 'Start Healenium Services with Docker Compose'
#    inputs:
#      containerregistrytype: 'Container Registry'
#      dockerComposeFile: '$(System.DefaultWorkingDirectory)/qa_auto/OneyFrance/infra/docker-compose.yaml'
#      action: 'Run services'
#      commandArguments: 'up -d'
#      buildImages: false

  - task: Bash@3
    displayName: 'Replace text'
    inputs:
      targetType: inline
      script: |
        buildId="$(Build.BuildId)"
        sed -i 's/${Build.BuildId}/'"$buildId"'/g' qa_auto/OneyFrance/conf/config.properties
        cat qa_auto/OneyFrance/conf/config.properties

  - task: Maven@3
    displayName: '[Run]: maven test & post result'
    inputs:
      mavenPomFile: 'qa_auto/OneyFrance/pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      testRunTitle: 'test'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - script: |
      curl -Lo allure.tgz "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.30.0/allure-commandline-2.30.0.tgz"
      tar -xzf allure.tgz
      ./allure-2.30.0/bin/allure generate --single-file qa_auto/OneyFrance/allure-results --clean -o qa_auto/OneyFrance/allure-report
    displayName: 'Generate Allure Results'
    condition: always()

  #- task: PublishBuildArtifacts@1
    #displayName: '[Publish]: videos'
    #condition: always()
    #inputs:
      #PathtoPublish: qa_auto/OneyFrance/src/test/java/Recording
      #ArtifactName: 'records'
      #publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    displayName: 'Allure reports html'
    condition: always()
    inputs:
      PathtoPublish: qa_auto/OneyFrance/allure-report
      ArtifactName: 'Reports'
      publishLocation: 'Container'
        #  - task: PowerShell@2
        #    displayName: '[Publish]: ms teams message'
        #    condition: always()
        #    inputs:
        #      filePath: qa_auto/OneyFrance/.azure/publish-to-msteams.ps1

#  - task: DockerCompose@1
#    displayName: 'Stop Healenium Services'
#    condition: always()
#    inputs:
#      containerregistrytype: 'Container Registry'
#      dockerComposeFile: '$(System.DefaultWorkingDirectory)/qa_auto/OneyFrance/infra/docker-compose.yaml'
#      action: 'Run a Docker Compose command'
#      dockerComposeCommand: 'down'